<<<<<<< Updated upstream
link:/i3_Berlin/wiki/Section-2-Assembly-of-the-Y-Unit[Next]
=======
link:i3_Berlin/wiki/Section-2-Assembly-of-the-Y-Unit[Next]
>>>>>>> Stashed changes

*About RepRap*

Welcome to this i3 Berlin building manual. Throughout this manual we are going to build and adjust the i3 Berlin 3D printer all the way through. 
  
But before we start doing anything we want to explain you the power and principles of open hardware, which we will illustrate with a brief history of the RepRap project.

Picture of i3 Berlin
<<<<<<< Updated upstream
link:/i3_Berlin/wiki/Section-1.1-History[Section 1.1]: The History of the RepRap project +

link:/i3_Berlin/wiki/Section-1.2-Tools-and-Parts[Section 1.2]: The Tools and Parts you need to build an i3 Berlin +

link:/i3_Berlin/wiki/Section-1.3-Preparing-Casings[Section 1.3]: The building starts with gluing the electronics cases +
=======
link:i3_Berlin/wiki/Section-1.1-History[Section 1.1]: The History of the RepRap project +

link:i3_Berlin/wiki/Section-1.2-Tools-and-Parts[Section 1.2]: The Tools and Parts you need to build an i3 Berlin +

link:i3_Berlin/wiki/Section-1.3-Preparing-Casings[Section 1.3]: The building starts with gluing the electronics cases +
>>>>>>> Stashed changes


*i3 Berlin Design overview*

3D printers come in many varieties. There are around 400 different open source models in circulation. We took the i3 design of Josef Prusa. This has been designed especially for easy assembly and is a comfortable all-round 3D printer to start with. We changed the original open design quite a bit, but essentially it is still the same printer. 

Our 'i3 Berlin' has further improved the ease of assembly. We made the looks more consistent and clean. We also added some extra functionality like easy folding mechanism, display and electronics casing. What you cannot see from the pictures is the effort we put in debugging the mechanical parts. We have tested the parts over and over again, so we are really sure that everything fits seamlessly. 





<<<<<<< Updated upstream
link:/i3_Berlin/wiki/Section-2-Assembly-of-the-Y-Unit[Next]
=======
link:i3_Berlin/wiki/Section-2-Assembly-of-the-Y-Unit[Next]
>>>>>>> Stashed changes

